---
abstract: 'Render heatmaps to your terminal'
author:
  - 'Richard Harris <richardjharris@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ANSI-Heatmap
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor::Fast: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/richardjharris/ANSI-Heatmap/issues
  repository: https://github.com/richardjharris/ANSI-Heatmap
version: 0.2
